name: ghcid-file-parser
version: '0.0.0.0'
github: "jship/ghcid-file-parser"
license: MIT
license-file: LICENSE.md
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: ghcid-file-parser synopsis
description: ghcid-file-parser description
category: Development

extra-source-files:
- package.yaml

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - aeson
  - attoparsec
  - base
  - bytestring
  - directory
  - text
  source-dirs: library

tests:
  ghcid-file-parser-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - aeson
    - base
    - bytestring
    - ghcid-file-parser
    - hspec

executables:
  ghcid-file-parser:
    source-dirs: app
    main: ghcid-file-parser.hs
    dependencies:
    - base
    - ghcid-file-parser
